# EECS 498-007/598-005 Assignment 1-1: PyTorch 101

Before we start, please put your name and UMID in following format

: Firstname LASTNAME, #00000000   //   e.g.) Justin JOHNSON, #12345678

**Your Answer:**   
Hello WORLD, #XXXXXXXX

# Introduction

Python 3 and [PyTorch](https://pytorch.org/) will be used throughout the semseter, so it is important to be familiar with them. This material in this notebook draws from http://cs231n.github.io/python-numpy-tutorial/ and https://github.com/kuleshov/cs228-material/blob/master/tutorials/python/cs228-python-tutorial.ipynb. This material focuses mainly on PyTorch.

This notebook will walk you through many of the important features of PyTorch that you will need to use throughout the semester. In some cells you will see code blocks that look like this:

```python
##############################################################################
# TODO: Write the equation for a line
##############################################################################
pass
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
```

You should replace the `pass` statement with your own code and leave the blocks intact, like this:

```python
##############################################################################
# TODO: Instructions for what you need to do
##############################################################################
y = m * x + b
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
```

When completing the notebook, please adhere to the following rules:
- Do not write or modify any code outside of code blocks
- Do not add or delete any cells from the notebook. You may add new cells to perform scatch work, but delete them before submitting.
- Run all cells before submitting. You will only get credit for code that has been run.

# Python 3


If you're unfamiliar with Python 3, here are some of the most common changes from Python 2 to look out for.


### Print is a function

In [ ]:
print("Hello!")

Without parentheses, printing will not work.

### Floating point division by default

In [ ]:
5 / 2

To do integer division, we use two backslashes:

In [ ]:
5 // 2

### No xrange

The xrange from Python 2 is now merged into "range" for Python 3 and there is no xrange in Python 3. In Python 3, range(3) does not create a list of 3 elements as it would in Python 2, rather just creates a more memory efficient iterator.

Hence,  
xrange in Python 3: Does not exist  
range in Python 3: Has very similar behavior to Python 2's xrange

In [ ]:
for i in range(3):
    print(i)

In [ ]:
range(3)

In [ ]:
# If need be, can use the following to get a similar behavior to Python 2's range:
print(list(range(3)))

# PyTorch

[PyTorch](https://pytorch.org/) is an open source machine learning framework. At its core, PyTorch provides a few key features:

- A multidimensional **Tensor** object, similar to [numpy](https://numpy.org/) but with GPU accelleration.
- An optimized **autograd** engine for automatically computing derivatives
- A clean, modular API for building and deploying **deep learning models**

We will use PyTorch for all programming assignments throughout the semester. This notebook will focus on the **Tensor API**, as it is the main part of PyTorch that we will use for the first few assignments.

You can find more information about PyTorch by following one of the [oficial tutorials](https://pytorch.org/tutorials/) or by [reading the documentation](https://pytorch.org/docs/1.1.0/).

To use PyTorch, we first need to import the `torch` package.

We also check the version; the assignments in this course will use PyTorch verion 1.1.0, since this is the default version in Google Colab.

In [ ]:
import torch
print(torch.__version__)

2.2.2


## Tensor Basics

### Creating and Accessing tensors

`torch` **张量(tensor)** 是一个多维值网格，所有值类型相同，并由非负整数的元组索引。维数的数量是张量的 **秩(rank)**；张量的 **形状(shape)** 是一个整数元组，给出数组在每个维度上的大小。

我们可以从嵌套的 Python 列表初始化 `torch` 张量。我们可以使用方括号访问或修改 PyTorch 张量的元素。

从 PyTorch 张量中访问一个元素会返回一个 PyTorch 标量；我们可以使用 `.item()` 方法将其转换为 Python 标量。

In [ ]:
# Create a rank 1 tensor from a Python list
a = torch.tensor([1, 2, 3])
print('Here is a:')
print(a)
print('type(a): ', type(a))
print('rank of a: ', a.dim())
print('a.shape: ', a.shape)

# Access elements using square brackets
print()
print('a[0]: ', a[0])
print('type(a[0]): ', type(a[0]))
print('type(a[0].item()): ', type(a[0].item()))

# Mutate elements using square brackets
a[1] = 10
print()
print('a after mutating:')
print(a)

Here is a:
tensor([1, 2, 3])
type(a):  <class 'torch.Tensor'>
rank of a:  1
a.shape:  torch.Size([3])

a[0]:  tensor(1)
type(a[0]):  <class 'torch.Tensor'>
type(a[0].item()):  <class 'int'>

a after mutating:
tensor([ 1, 10,  3])


上面的例子显示了一个一维张量；我们同样可以创建具有二维或更多维度的张量：

In [ ]:
# Create a two-dimensional tensor
b = torch.tensor([[1, 2, 3], [4, 5, 5]])
print('Here is b:')
print(b)
print('rank of b:', b.dim())
print('b.shape: ', b.shape)

# Access elements from a multidimensional tensor
print()
print('b[0, 1]:', b[0, 1])
print('b[1, 2]:', b[1, 2])

# Mutate elements of a multidimensional tensor
b[1, 1] = 100
print()
print('b after mutating:')
print(b)

Here is b:
tensor([[1, 2, 3],
        [4, 5, 5]])
rank of b: 2
b.shape:  torch.Size([2, 3])

b[0, 1]: tensor(2)
b[1, 2]: tensor(5)

b after mutating:
tensor([[  1,   2,   3],
        [  4, 100,   5]])


Now it's your turn:

1. Construct a tensor `c` of shape `(3, 2)` filled with zeros by initializing from nested Python lists.
2. Then set element `(0, 1)` to 10, and element `(1, 0)` to 100:

In [ ]:
c = None
################################################################################
# TODO: Construct a tensor c filled with all zeros, initializing from nested   #
# Python lists.                                                                #
################################################################################
# Replace "pass" statement with your code
c = torch.tensor([[0,0],[0,0],[0,0]])
################################################################################
#                              END OF YOUR CODE                                #
################################################################################
print('c is a tensor: ', torch.is_tensor(c))
print('Correct shape: ', c.shape == (3, 2))
print('All zeros: ', (c == 0).all().item() == 1)

################################################################################
# TODO: Set element (0, 1) of c to 10, and element (1, 0) of c to 100.         #
################################################################################
# Replace "pass" statement with your code
c[0,1], c[1,0] = 10, 100
################################################################################
#                              END OF YOUR CODE                                #
################################################################################
print('\nAfter mutating:')
print('Correct shape: ', c.shape == (3, 2))
print('c[0, 1] correct: ', c[0, 1] == 10)
print('c[1, 0] correct: ', c[1, 0] == 100)
print('Rest of c is still zero: ', (c == 0).sum().item() == 4)

c is a tensor:  True
Correct shape:  True
All zeros:  True

After mutating:
Correct shape:  True
c[0, 1] correct:  tensor(True)
c[1, 0] correct:  tensor(True)
Rest of c is still zero:  True


### Tensor constructors

PyTorch 提供了许多方便的方法来构建张量；这避免了使用 Python 列表的需要。例如：

- [`torch.zeros`](https://pytorch.org/docs/1.1.0/torch.html#torch.zeros): 创建一个全为0的张量
- [`torch.ones`](https://pytorch.org/docs/1.1.0/torch.html#torch.ones): 创建一个全为1的张量
- [`torch.rand`](https://pytorch.org/docs/1.1.0/torch.html#torch.rand): 创建一个具有均匀随机数的张量

You can find a full list of tensor creation operations [in the documentation](https://pytorch.org/docs/1.1.0/torch.html#creation-ops).

In [ ]:
# 全零张量
a = torch.zeros(2, 3)
print('tensor of zeros:')
print(a)

# 全1张量
b = torch.ones(1, 2)
print('\ntensor of ones:')
print(b)

# 3x3 对角矩阵
c = torch.eye(3)
print('\nidentity matrix:')
print(c)

# 随机矩阵
d = torch.rand(4, 5)
print('\nrandom tensor:')
print(d)

tensor of zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

tensor of ones:
tensor([[1., 1.]])

identity matrix:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

random tensor:
tensor([[0.4163, 0.9638, 0.6795, 0.4539, 0.1354],
        [0.8309, 0.1014, 0.1678, 0.1838, 0.9939],
        [0.1839, 0.3927, 0.9846, 0.1630, 0.1193],
        [0.8057, 0.3750, 0.8874, 0.3205, 0.1990]])


轮到你了：使用张量创建函数创建一个形状为 (2, 3, 4) 的张量，全部填充为 7。

Hint: [`torch.full`](https://pytorch.org/docs/1.1.0/torch.html#torch.full)

In [ ]:
e = None
################################################################################
# TODO: Create a tensor of shape (2, 3, 4) filled entirely with 7, stored in e #
################################################################################
# Replace "pass" statement with your code
e = torch.full((2,3,4),7)
################################################################################
#                              END OF YOUR CODE                                #
################################################################################
print('e is a tensor:', torch.is_tensor(e))
print('e has correct shape: ', e.shape == (2, 3, 4))
print('e is filled with sevens: ', (e == 7).all().item() == 1)

e is a tensor: True
e has correct shape:  True
e is filled with sevens:  True


### 数据类型

在上面的例子中，您可能已经注意到我们的一些张量包含浮点值，而其他张量包含整数值。

PyTorch 可以用 [各种类型的数值](https://pytorch.org/docs/1.1.0/tensor_attributes.html#torch-dtype) 构造张量。 当你创建一个张量时，PyTorch 会尝试猜测数据类型；构造张量的函数通常有一个 `dtype` 参数，你可以用它来显式指定数据类型。

每个张量都有一个 `dtype` 属性，您可以用来检查其数据类型：

In [ ]:
# 让 torch 自动选择
x0 = torch.tensor([1, 2])   # List of integers
x1 = torch.tensor([1., 2.]) # List of floats
x2 = torch.tensor([1., 2])  # Mixed list
print('dtype when torch chooses for us:')
print('List of integers:', x0.dtype)
print('List of floats:', x1.dtype)
print('Mixed list:', x2.dtype)

# 指定数据类型
y0 = torch.tensor([1, 2], dtype=torch.float32)  # 32-bit float
y1 = torch.tensor([1, 2], dtype=torch.int32)    # 32-bit (signed) integer
y2 = torch.tensor([1, 2], dtype=torch.int64)    # 64-bit (signed) integer
print('\ndtype when we force a datatype:')
print('32-bit float: ', y0.dtype)
print('32-bit integer: ', y1.dtype)
print('64-bit integer: ', y2.dtype)

# 使用其他构建张量方法时指定数字类型
z0 = torch.ones(1, 2)  # Let torch choose for us
z1 = torch.ones(1, 2, dtype=torch.int16) # 16-bit (signed) integer
z2 = torch.ones(1, 2, dtype=torch.uint8) # 8-bit (unsigned) integer
print('\ntorch.ones with different dtypes')
print('default dtype:', z0.dtype)
print('16-bit integer:', z1.dtype)
print('8-bit unsigned integer:', z2.dtype)

dtype when torch chooses for us:
List of integers: torch.int64
List of floats: torch.float32
Mixed list: torch.float32

dtype when we force a datatype:
32-bit float:  torch.float32
32-bit integer:  torch.int32
64-bit integer:  torch.int64

torch.ones with different dtypes
default dtype: torch.float32
16-bit integer: torch.int16
8-bit unsigned integer: torch.uint8


转换（**cast**）一个张量的数据类型可以使用[`.to()`](https://pytorch.org/docs/1.1.0/tensors.html#torch.Tensor.to)方法; 其他简便方法还有类似[`.float()`](https://pytorch.org/docs/1.1.0/tensors.html#torch.Tensor.float) （等价 `self.to(torch.float32)`）和 [`.long()`](https://pytorch.org/docs/1.1.0/tensors.html#torch.Tensor.long)（等价`self.to(torch.int64)`）

In [ ]:
x0 = torch.eye(3, dtype=torch.int64)
x1 = x0.float()  # Cast to 32-bit float
x2 = x0.double() # Cast to 64-bit float
x3 = x0.to(torch.float32) # Alternate way to cast to 32-bit float
x4 = x0.to(torch.float64) # Alternate way to cast to 64-bit float
print('x0:', x0.dtype)
print('x1:', x1.dtype)
print('x2:', x2.dtype)
print('x3:', x3.dtype)
print('x4:', x4.dtype)

x0: torch.int64
x1: torch.float32
x2: torch.float64
x3: torch.float32
x4: torch.float64


PyTorch 提供了几种方法来创建与另一个张量具有相同数据类型的张量：

- PyTorch 可以使用类似于 [`torch.new_zeros()`](https://pytorch.org/docs/1.1.0/torch.html#torch.zeros_like) 的方式创建指定与指定张量形状和数据类型相同的张量。
- 张量对象具有实例方法，例如[`.new_zeros()`](https://pytorch.org/docs/1.1.0/tensors.html#torch.Tensor.new_zeros)，可以创建相同类型但形状可能不同的张量。
- 对于张量实例，可以在 [`.to()`](https://pytorch.org/docs/1.1.0/tensors.html#torch.Tensor.to) 内将另一个张量作为参数, 将实例张量的数据类型与指定张量保持一致。

In [ ]:
x0 = torch.eye(3, dtype=torch.float64)  # Shape (3, 3), dtype torch.float64
x1 = torch.zeros_like(x0)               # Shape (3, 3), dtype torch.float64
x2 = x0.new_zeros(4, 5)                 # Shape (4, 5), dtype torch.float64
x3 = torch.ones(6, 7).to(x0)            # Shape (6, 7), dtype torch.float64)
print('x0 shape is %r, dtype is %r' % (x0.shape, x0.dtype))
print('x1 shape is %r, dtype is %r' % (x1.shape, x1.dtype))
print('x2 shape is %r, dtype is %r' % (x2.shape, x2.dtype))
print('x3 shape is %r, dtype is %r' % (x3.shape, x3.dtype))

Your turn: Create a 64-bit floating-point tensor of shape (6,) (six-element vector) filled with evenly-spaced values between 10 and 20.

Hint: [`torch.linspace`](https://pytorch.org/docs/stable/torch.html#torch.linspace)

In [ ]:
x = None
##############################################################################
# TODO: Make x contain a six-element vector of 64-bit floating-bit values,   #
# evenly spaced between 10 and 20.                                           #
##############################################################################
# Replace "pass" statement with your code
x = torch.linspace(start=10, end=20, steps=6).to(torch.float64)
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
print('x is a tensor: ', torch.is_tensor(x))
print('x has correct shape: ', x.shape == (6,))
print('x has correct dtype: ', x.dtype == torch.float64)
y = [10, 12, 14, 16, 18, 20]
correct_vals = all(a.item() == b for a, b in zip(x, y))
print('x has correct valus: ', correct_vals)

x is a tensor:  True
x has correct shape:  True
x has correct dtype:  True
x has correct valus:  True


尽管 PyTorch 提供了大量数字数据类型，但最常用的数据类型是

- torch.float32`：标准浮点类型；用于存储可学习参数、网络激活等。几乎所有算术运算都使用这种类型。

- `torch.int64`：通常用于存储指数

- `torch.uint8`：通常用于存储布尔值，其中 0 表示假，1 表示真。

- `torch.float16`：用于混合精度算术，通常在英伟达™（NVIDIA®）图形处理器上使用[Tensor Cores](https://www.nvidia.com/en-us/data-center/tensorcore/)。在本课程中，您不需要担心这种数据类型。

请注意，PyTorch 1.2.0 版本引入了一个新的 `torch.bool` 数据类型，用于保存布尔值。然而，在早期版本（包括我们在本课程中使用的 1.1.0）中，您会看到 `torch.uint8` 被用来保存布尔值。

## 张量索引

我们已经了解了如何获取和设置PyTorch张量的各个元素。PyTorch还提供了许多其他方法来索引张量。熟悉这些不同的选项可以轻松地修改张量的不同部分。

### 切片索引

与 Python 列表和 numpy 数组类似，PyTorch 张量可以使用 `start:stop` 或 `start:stop:step` 语法进行**切片**。`stop` 索引始终是非包含性的：它是切片中不包含的第一个元素。

起始和结束索引可以是负数，在这种情况下，它们从张量的末尾向后计数。

In [ ]:
a = torch.tensor([0, 11, 22, 33, 44, 55, 66])
print(0, a)        # (0) 原张量
print(1, a[2:5])   # (1) 张量的第2至第4索引的元素
print(2, a[2:])    # (2) 索引2及之后的元素
print(3, a[:5])    # (3) 索引5之前的元素
print(4, a[:])     # (4) 所有元素
print(5, a[1:5:2]) # (5) 索引 1 至 5 之间的每第二个元素（含索引1）
print(6, a[:-1])   # (6) 去除最后一个元素
print(7, a[-4::2]) # (7) 从倒数第四个元素开始，每第二个元素

0 tensor([ 0, 11, 22, 33, 44, 55, 66])
1 tensor([22, 33, 44])
2 tensor([22, 33, 44, 55, 66])
3 tensor([ 0, 11, 22, 33, 44])
4 tensor([ 0, 11, 22, 33, 44, 55, 66])
5 tensor([11, 33])
6 tensor([ 0, 11, 22, 33, 44, 55])
7 tensor([33, 55])


对于多维张量，您可以为张量的每个维度提供一个切片或整数，以提取不同类型的子张量：

In [ ]:
# Create the following rank 2 tensor with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = torch.tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print('Original tensor:')
print(a)
print('shape: ', a.shape)

# 提取第一行
print('\nSingle row:')
print(a[1, :])
print(a[1])  # Gives the same result; we can omit : for trailing dimensions
print('shape: ', a[1].shape)

#提取第一列
print('\nSingle column:')
print(a[:, 1])
print('shape: ', a[:, 1].shape)

# 提取前两行的后三列
print('\nFirst two rows, last two columns:')
print(a[:2, -3:])
print('shape: ', a[:2, -3:].shape)

# 获取每隔一行，以及索引为1和2的列。
print('\nEvery other row, middle columns:')
print(a[::2, 1:3])
print('shape: ', a[::2, 1:3].shape)

Original tensor:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
shape:  torch.Size([3, 4])

Single row:
tensor([5, 6, 7, 8])
tensor([5, 6, 7, 8])
shape:  torch.Size([4])

Single column:
tensor([ 2,  6, 10])
shape:  torch.Size([3])

First two rows, last two columns:
tensor([[2, 3, 4],
        [6, 7, 8]])
shape:  torch.Size([2, 3])

Every other row, middle columns:
tensor([[ 2,  3],
        [10, 11]])
shape:  torch.Size([2, 2])


访问张量的单行或单列有两种常见方法：使用单个数值会将秩减少1，使用长度为1的切片会保持相同的秩。请注意，这与MATLAB的行为不同。

In [ ]:
# Create the following rank 2 tensor with shape (3, 4)
a = torch.tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print('Original tensor')
print(a)

row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print('\nTwo ways of accessing a single row:')
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

# 当访问列时，我们可以做出同样的区分：
col_r1 = a[:, 1] # 行向量
col_r2 = a[:, 1:2] # 列向量
print('\nTwo ways of accessing a single column:')
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

Original tensor
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Two ways of accessing a single row:
tensor([5, 6, 7, 8]) torch.Size([4])
tensor([[5, 6, 7, 8]]) torch.Size([1, 4])

Two ways of accessing a single column:
tensor([ 2,  6, 10]) torch.Size([3])
tensor([[ 2],
        [ 6],
        [10]]) torch.Size([3, 1])


对张量进行切片会返回相同数据的 **视图（view）** ，因此修改它也会修改原始张量。为了避免这种情况，可以使用 `clone()` 方法来复制一个张量。

In [ ]:
# Create a tensor, a slice, and a clone of a slice
a = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
b = a[0, 1:]
c = a[0, 1:].clone()
print('Before mutating:')
print(a)
print(b)
print(c)

a[0, 1] = 20  # a[0, 1] and b[0] point to the same element
b[1] = 30     # b[1] and a[0, 2] point to the same element
c[2] = 40     # c is a clone, so it has its own data
print('\nAfter mutating:')
print(a)
print(b)
print(c)

print(a.storage().data_ptr() == c.storage().data_ptr())

Before mutating:
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([2, 3, 4])
tensor([2, 3, 4])

After mutating:
tensor([[ 1, 20, 30,  4],
        [ 5,  6,  7,  8]])
tensor([20, 30,  4])
tensor([ 2,  3, 40])
False


/var/folders/1x/3jr_414d291dg6ht5ymfdb1c0000gn/T/ipykernel_39055/3860217186.py:18: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print(a.storage().data_ptr() == c.storage().data_ptr())


Your turn: practice indexing tensors with slices

In [ ]:
# We will use this helper function to check your results
def check(orig, actual, expected):
  expected = torch.tensor(expected)
  same_elements = (actual == expected).all().item() == 1
  same_storage = (orig.storage().data_ptr() == actual.storage().data_ptr())
  return same_elements and same_storage

In [ ]:
# Create the following rank 2 tensor of shape (3, 5)
# [[ 1  2  3  4  5]
#  [ 6  7  8  9 10]
#  [11 12 13 14 15]]
a = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 8, 10], [11, 12, 13, 14, 15]])

b, c, d, e = None, None, None, None
##############################################################################
# TODO: Extract the last row of a, and store it in b; it should have rank 1. #
##############################################################################
# Replace "pass" statement with your code
b = a[-1,:]
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
print('b correct:', check(a, b, [11, 12, 13, 14, 15]))

##############################################################################
# TODO: Extract the third col of a, and store it in c; it should have rank 2 #
##############################################################################
# Replace "pass" statement with your code
c = a[:,2:2]
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
print('c correct:', check(a, c, [[3], [8], [13]]))

##############################################################################
# TODO: Use slicing to extract the first two rows and first three columns    #
# from a; store the result into d.                                           #
##############################################################################
# Replace "pass" statement with your code
d = a[:2,:3]
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
print('d correct:', check(a, d, [[1, 2, 3], [6, 7, 8]]))

##############################################################################
# TODO: Use slicing to extract a subtensor of a consisting of rows 0 and 2   #
# and columns 1 and 4.                                                       #
##############################################################################
# Replace "pass" statement with your code
e = a[[0, 2]][:, [1, 4]]
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
print('e correct:', check(a, e, [[2, 5], [12, 15]]))

b correct: True
c correct: True
d correct: True
e correct: False


/var/folders/1x/3jr_414d291dg6ht5ymfdb1c0000gn/T/ipykernel_43812/3939471097.py:5: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  same_storage = (orig.storage().data_ptr() == actual.storage().data_ptr())


到目前为止，我们已经使用切片来**访问**子张量；我们也可以通过编写赋值表达式来使用切片**修改**子张量，其中左侧是切片表达式，右侧是常量或形状正确的张量：

In [ ]:
a = torch.zeros(2, 4, dtype=torch.int64)
a[:, :2] = 1
a[:, 2:] = torch.tensor([[2, 3], [4, 5]])
print(a)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])
tensor([[1, 1, 2, 3],
        [1, 1, 4, 5]])


Your turn: use slicing assignment to modify a tensor:

In [ ]:
x = torch.zeros(4, 6, dtype=torch.int64)
##############################################################################
# TODO: Use slicing to modify the tensor x so it has the following contents: #
#     [[1, 0, 2, 2, 2, 2],                                                   #
#      [0, 1, 2, 2, 2, 2],                                                   #
#      [3, 4, 3, 4, 5, 5],                                                   #
#      [3, 4, 3, 4, 5, 5]]                                                   #
# This can be achieved using five slicing assignment operations.             #
##############################################################################
# Replace "pass" statement with your code
x[:2,:2] = torch.eye(2)
x[:2,2:] = torch.ones(2,4) * 2
x[2:,4:] = torch.ones(2,2)* 5
x[2:,:4] = torch.tensor([[3,4,3,4],[3,4,3,4]])
print(x)
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################

expected = [
    [1, 0, 2, 2, 2, 2],
    [0, 1, 2, 2, 2, 2],
    [3, 4, 3, 4, 5, 5],
    [3, 4, 3, 4, 5, 5],
]
print('correct:', x.tolist() == expected)

tensor([[1, 0, 2, 2, 2, 2],
        [0, 1, 2, 2, 2, 2],
        [3, 4, 3, 4, 5, 5],
        [3, 4, 3, 4, 5, 5]])
correct: True


### 整数张量索引

当你使用切片对torch张量进行索引时，结果张量视图将始终是原始张量的一个子数组。这很强大，但可能有些限制。

我们也可以使用 **索引数组** 来索引张量；这让我们在构建新张量时比使用切片有更多的灵活性。

例如，我们可以使用索引数组重新排序张量的行或列：

In [ ]:
# Create the following rank 2 tensor with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print('Original tensor:')
print(a)

# 通过重新排列 a 的行创建一个形状为 (5, 4) 的新张量：

# - 前两行与 a 的第一行相同
# - 第三行与 a 的最后一行相同
# - 第四和第五行与 a 的第二行相同
idx = [0, 0, 2, 1, 1]  # index arrays can be Python lists of integers
print('\nReordered rows:')
print(a[idx])

# 通过反转a的列创建一个形状为(3, 4)的新张量。
idx = torch.tensor([3, 2, 1, 0])  # Index arrays can be int64 torch tensors
print('\nReordered columns:')
print(a[:, idx])

Original tensor:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Reordered rows:
tensor([[ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [ 5,  6,  7,  8],
        [ 5,  6,  7,  8]])

Reordered columns:
tensor([[ 4,  3,  2,  1],
        [ 8,  7,  6,  5],
        [12, 11, 10,  9]])


More generally, given index arrays `idx0` and `idx1` with `N` elements each, `a[idx0, idx1]` is equivalent to:

```
torch.tensor([
  a[idx0[0], idx1[0]],
  a[idx0[1], idx1[1]],
  ...,
  a[idx0[N - 1], idx1[N - 1]]
])
```

(A similar pattern extends to tensors with more than two dimensions)

We can for example use this to get or set the diagonal of a tensor:

In [ ]:
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Original tensor:')
print(a)

idx = [0, 1, 2]
print('\nGet the diagonal:')
print(a[idx, idx])

# Modify the diagonal
a[idx, idx] = torch.tensor([11, 22, 33])
print('\nAfter setting the diagonal:')
print(a)

Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Get the diagonal:
tensor([1, 5, 9])

After setting the diagonal:
tensor([[11,  2,  3],
        [ 4, 22,  6],
        [ 7,  8, 33]])


使用整数数组索引的一个有用技巧是从矩阵的每一行或每一列中选择或更改一个元素：

In [ ]:
# Create a new tensor from which we will select elements
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print('Original tensor:')
print(a)

# Take on element from each row of a:
# from row 0, take element 1;
# from row 1, take element 2;
# from row 2, take element 1;
# from row 3, take element 0
idx0 = torch.arange(a.shape[0])  # Quick way to build [0, 1, 2, 3]
idx1 = torch.tensor([1, 2, 1, 0])
print('\nSelect one element from each row:')
print(a[idx0, idx1])

# Now set each of those elements to zero
a[idx0, idx1] = 0
print('\nAfter modifying one element from each row:')
print(a)

Original tensor:
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

Select one element from each row:
tensor([ 2,  6,  8, 10])

After modifying one element from each row:
tensor([[ 1,  0,  3],
        [ 4,  5,  0],
        [ 7,  0,  9],
        [ 0, 11, 12]])


Your turn: practice with integer array indexing

In [ ]:
# Build a tensor of shape (4, 3):
# [[ 1,  2,  3],
#  [ 4,  5,  6],
#  [ 7,  8,  9],
#  [10, 11, 12]]
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print('Here is a:')
print(a)

b, c, d = None, None, None
##############################################################################
# TODO: Use integer array indexing to create a tensor of shape (4, 4) where: #
# - The first two columns are the same as the first column of a              #
# - The next column is the same as the third column of a                     #
# - The last column is the same as the second column of a                    #
# Store the resulting tensor in b.                                           #
##############################################################################
# Replace "pass" statement with your code
idx2 = torch.tensor([0,0,2,1])
b = a[:,idx2]
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
print('\nHere is b:')
print(b)
expected = [[1, 1, 3, 2], [4, 4, 6, 5], [7, 7, 9, 8], [10, 10, 12, 11]]
print('b correct:', b.tolist() == expected)

##############################################################################
# TODO: Use integer array indexing to create a new tensor which is the same  #
# as a, but has its rows reversed. Store the result in c.                    #
##############################################################################
# Replace "pass" statement with your code
idx3 = torch.tensor([3,2,1,0])
c = a[idx3, :]
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
print('\nHere is c:')
print(c)
expected = [[10, 11, 12], [7, 8, 9], [4, 5, 6], [1, 2, 3]]
print('c correct:', c.tolist() == expected)

##############################################################################
# TODO: Use integer array indexing to create a new tensor by selecting one   #
# element from each column of a:                                             #
# - From the first column, take the second element.                          #
# - From the second column, take the first element.                          #
# - From the third column, take the fourth element.                          #
# Store the result in d.                                                     #
##############################################################################
# Replace "pass" statement with your code
idx4 = [0,1,2]
idx5 = [1,0,3]
d = a[idx5,idx4]
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
print('\nHere is d:')
print(d)
expected = [4, 2, 12]
print('d correct:', d.tolist() == expected)

Here is a:
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

Here is b:
tensor([[ 1,  1,  3,  2],
        [ 4,  4,  6,  5],
        [ 7,  7,  9,  8],
        [10, 10, 12, 11]])
b correct: True

Here is c:
tensor([[10, 11, 12],
        [ 7,  8,  9],
        [ 4,  5,  6],
        [ 1,  2,  3]])
c correct: True

Here is d:
tensor([ 4,  2, 12])
d correct: True


### 布尔值索引

布尔张量索引允许您根据布尔掩码选择张量的任意元素。通常，这种类型的索引用于选择或修改满足某些条件的张量元素。

在PyTorch中，我们使用dtype为`torch.uint8`的张量来保存布尔掩码；0表示假，1表示真。

（PyTorch版本1.2.0引入了`torch.bool`类型的张量，用于布尔掩码，而不是使用`torch.uint8`。然而在本课程中，我们使用的是PyTorch 1.1.0）

In [ ]:
a = torch.tensor([[1,2], [3, 4], [5, 6]])
print('Original tensor:')
print(a)

# 找出 a 中大于 3 的元素。mask 与 a 形状相同，其中每个 mask 元素指示 a 的相应元素是否大于 3。
mask = (a > 3)
print('\nMask tensor:')
print(mask)

# We can use the mask to construct a rank-1 tensor containing the elements of a
# that are selected by the mask
print('\nSelecting elements with the mask:')
print(a[mask])

# We can also use boolean masks to modify tensors; for example this sets all
# elements <= 3 to zero:
a[a <= 3] = 0
print('\nAfter modifying with a mask:')
print(a)

Original tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Mask tensor:
tensor([[False, False],
        [False,  True],
        [ True,  True]])

Selecting elements with the mask:
tensor([4, 5, 6])

After modifying with a mask:
tensor([[0, 0],
        [0, 4],
        [5, 6]])


Your turn: practice with boolean masks by implementing the following function:

In [ ]:
def num_negative(x):
  """
  Return the number of negative values in the tensor x

  Inputs:
  - x: A tensor of any shape

  Returns:
  - num_neg: Number of negative values in x
  """
  num_neg = 0
  ##############################################################################
  # TODO: Use boolean masks to count the number of negative elements in x.     #
  ##############################################################################
  # Replace "pass" statement with your code
  num_neg = torch.sum(x < 0).item()
  ##############################################################################
  #                             END OF YOUR CODE                               #
  ##############################################################################
  return num_neg

# Make a few test cases
torch.manual_seed(598)
x0 = torch.tensor([[-1, -1, 0], [0, 1, 2], [3, 4, 5]])
x1 = torch.tensor([0, 1, 2, 3])
x2 = torch.randn(100, 100)
assert num_negative(x0) == 2
assert num_negative(x1) == 0
assert num_negative(x2) == 4984
print('num_negative seems to be correct!')

num_negative seems to be correct!


现在实现一个函数，从一个Python整数列表创建一个 **独热向量(one-hot vector)** 矩阵。

一个整数 $n$ 的独热向量是在其第 $n$ 个位置为1，其他位置为0的向量。独热向量通常用于在机器学习模型中表示分类变量。

例如，给定一个整数列表`[1, 4, 3, 2]`，你的函数应该生成张量：

```
[[0 1 0 0 0],
 [0 0 0 0 1],
 [0 0 0 1 0],
 [0 0 1 0 0]]
```

Here the first row corresponds to the first element of the list: it has a one at index 1, and zeros at all other indices. The second row corresponds to the second element of the list: it has a one at index 4, and zeros at all other indices. The other rows follow the same pattern.

In [ ]:
def make_one_hot(x):
  """
  Construct a tensor of one-hot-vectors from a list of Python integers.

  Input:
  - x: A list of N ints

  Returns:
  - y: A tensor of shape (N, C) where C = 1 + max(x) is one more than the max
       value in x. The nth row of y is a one-hot-vector representation of x[n];
       In other words, if x[n] = c then y[n, c] = 1; all other elements of y are
       zeros.
  """
  y = None
  ##############################################################################
  # TODO: Complete the implementation of this function.                        #
  ##############################################################################
  # Replace "pass" statement with your code
  rows = len(x)
  columns = max(x) + 1
  y = torch.zeros(rows,columns)
  for i in range(rows):
    y[i,x[i]] = 1
  ##############################################################################
  #                             END OF YOUR CODE                               #
  ##############################################################################
  return y

Now check your implementation:

In [ ]:
def check_one_hot(x, y):
  C = y.shape[1]
  for i, n in enumerate(x):
    if n >= C: return False
    for j in range(C):
      expected = 1.0 if j == n else 0.0
      if y[i, j].item() != expected: return False
  return True

x0 = [1, 4, 3, 2]
y0 = make_one_hot(x0)
print('Here is y0:')
print(y0)
assert check_one_hot(x0, y0), 'y0 is wrong'

x1 = [1, 3, 5, 7, 6, 2]
y1 = make_one_hot(x1)
print('\nHere is y1:')
print(y1)
assert check_one_hot(x1, y1), 'y1 is wrong'

print('all checks pass!')

Here is y0:
tensor([[0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.]])

Here is y1:
tensor([[0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.]])
all checks pass!


## Reshaping operations

### View

PyTorch提供了多种方法来操作张量的形状。 最简单的是[`.view()`](https://pytorch.org/docs/1.1.0/tensors.html#torch.Tensor.view): 这将返回一个与其输入具有相同元素数量但形状不同的新张量。

我们可以使用 `.view()` 将矩阵展平成向量，并将秩为1的向量转换为秩为2的行或列矩阵：

In [ ]:
x0 = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
print('Original tensor:')
print(x0)
print('shape:', x0.shape)

# Flatten x0 into a rank 1 vector of shape (8,)
x1 = x0.view(8)
print('\nFlattened tensor:')
print(x1)
print('shape:', x1.shape)

# Convert x1 to a rank 2 "row vector" of shape (1, 8)
x2 = x1.view(1, 8)
print('\nRow vector:')
print(x2)
print('shape:', x2.shape)

# Convert x1 to a rank 2 "column vector" of shape (8, 1)
x3 = x1.view(8, 1)
print('\nColumn vector:')
print(x3)
print('shape:', x3.shape)

# Convert x1 to a rank 3 tensor of shape (2, 2, 2):
x4 = x1.view(2, 2, 2)
print('\nRank 3 tensor:')
print(x4)
print('shape:', x4.shape)

Original tensor:
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
shape: torch.Size([2, 4])

Flattened tensor:
tensor([1, 2, 3, 4, 5, 6, 7, 8])
shape: torch.Size([8])

Row vector:
tensor([[1, 2, 3, 4, 5, 6, 7, 8]])
shape: torch.Size([1, 8])

Column vector:
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])
shape: torch.Size([8, 1])

Rank 3 tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
shape: torch.Size([2, 2, 2])


为了方便，调用 `.view()` 时可以包含一个 -1 参数；这会在该维度上放置足够的元素，使输出与输入具有相同的形状。这使得以一种与张量形状无关的方式编写一些重塑操作变得容易：

In [ ]:
# We can reuse these functions for tensors of different shapes
def flatten(x):
  return x.view(-1)

def make_row_vec(x):
  return x.view(1, -1)

x0 = torch.tensor([[1, 2, 3], [4, 5, 6]])
x0_flat = flatten(x0)
x0_row = make_row_vec(x0)
print('x0:')
print(x0)
print('x0_flat:')
print(x0_flat)
print('x0_row:')
print(x0_row)

x1 = torch.tensor([[1, 2], [3, 4]])
x1_flat = flatten(x1)
x1_row = make_row_vec(x1)
print('\nx1:')
print(x1)
print('x1_flat:')
print(x1_flat)
print('x1_row:')
print(x1_row)

x0:
tensor([[1, 2, 3],
        [4, 5, 6]])
x0_flat:
tensor([1, 2, 3, 4, 5, 6])
x0_row:
tensor([[1, 2, 3, 4, 5, 6]])

x1:
tensor([[1, 2],
        [3, 4]])
x1_flat:
tensor([1, 2, 3, 4])
x1_row:
tensor([[1, 2, 3, 4]])


顾名思义，`.view() `返回的张量与输入的张量共享相同的数据，因此对其中一个张量的更改会影响另一个张量，反之亦然：

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x_flat = x.view(-1)
print('x before modifying:')
print(x)
print('x_flat before modifying:')
print(x_flat)

x[0, 0] = 10   # x[0, 0] and x_flat[0] point to the same data
x_flat[1] = 20 # x_flat[1] and x[0, 1] point to the same data

print('\nx after modifying:')
print(x)
print('x_flat after modifying:')
print(x_flat)

x before modifying:
tensor([[1, 2, 3],
        [4, 5, 6]])
x_flat before modifying:
tensor([1, 2, 3, 4, 5, 6])

x after modifying:
tensor([[10, 20,  3],
        [ 4,  5,  6]])
x_flat after modifying:
tensor([10, 20,  3,  4,  5,  6])


### Swapping axes

另一种常见的重塑操作是转置矩阵。如果你尝试使用 `.view()` 转置矩阵，可能会感到惊讶：`view()` 函数以行优先顺序获取元素，因此**你不能使用 `.view()` 转置矩阵**。

通常，你应该只使用 `.view()` 来为张量添加新维度，或折叠张量的相邻维度。

对于其他类型的重塑操作，通常需要使用可以交换张量轴的函数。最简单的此类函数是`.t()`，专门用于转置矩阵。它是`torch`模块中的一个[函数](https://pytorch.org/docs/1.1.0/torch.html#torch.t),以及一个 [tensor 实例的方法](https://pytorch.org/docs/1.1.0/tensors.html#torch.Tensor.t):

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print('Original matrix:')
print(x)
print('\nTransposing with view DOES NOT WORK!')
print(x.view(3, 2))
print('\nTransposed matrix:')
print(torch.t(x))
print(x.t())

Original matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])

Transposing with view DOES NOT WORK!
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Transposed matrix:
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


对于高于二维的张量，可使用函数 [`torch.transpose`](https://pytorch.org/docs/1.1.0/torch.html#torch.transpose) 交换任意维度, 或者 [`.permute`](https://pytorch.org/docs/1.1.0/tensors.html#torch.Tensor.permute)方法排列任意维数:

In [ ]:
# Create a tensor of shape (2, 3, 4)
x0 = torch.tensor([
     [[1,  2,  3,  4],
      [5,  6,  7,  8],
      [9, 10, 11, 12]],
     [[13, 14, 15, 16],
      [17, 18, 19, 20],
      [21, 22, 23, 24]]])
print('Original tensor:')
print(x0)
print('shape:', x0.shape)

# Swap axes 1 and 2; shape is (2, 4, 3)
x1 = x0.transpose(1, 2)
print('\nSwap axes 1 and 2:')
print(x1)
print(x1.shape)

# Permute axes; the argument (1, 2, 0) means:
# - Make the old dimension 1 appear at dimension 0;
# - Make the old dimension 2 appear at dimension 1;
# - Make the old dimension 0 appear at dimension 2
# This results in a tensor of shape (3, 4, 2)
x2 = x0.permute(1, 2, 0)
print('\nPermute axes')
print(x2)
print('shape:', x2.shape)

Original tensor:
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])
shape: torch.Size([2, 3, 4])

Swap axes 1 and 2:
tensor([[[ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11],
         [ 4,  8, 12]],

        [[13, 17, 21],
         [14, 18, 22],
         [15, 19, 23],
         [16, 20, 24]]])
torch.Size([2, 4, 3])

Permute axes
tensor([[[ 1, 13],
         [ 2, 14],
         [ 3, 15],
         [ 4, 16]],

        [[ 5, 17],
         [ 6, 18],
         [ 7, 19],
         [ 8, 20]],

        [[ 9, 21],
         [10, 22],
         [11, 23],
         [12, 24]]])
shape: torch.Size([3, 4, 2])


### Contiguous tensors

有些重塑操作组合会失败，并伴有隐性错误。具体原因与实现张量和张量视图的方式有关，超出了本作业的范围。 However if you're curious, [this blog post by Edward Yang](http://blog.ezyang.com/2019/05/pytorch-internals/) gives a clear explanation of the problem.

What you need to know is that you can typically overcome these sorts of errors by either by calling [`.contiguous()`](https://pytorch.org/docs/1.1.0/tensors.html#torch.Tensor.contiguous) before `.view()`, or by using [`.reshape()`](https://pytorch.org/docs/1.1.0/tensors.html#torch.Tensor.reshape) instead of `.view()`.

In [ ]:
x0 = torch.randn(2, 3, 4)

try:
  # This sequence of reshape operations will crash
  x1 = x0.transpose(1, 2).view(8, 3)
except RuntimeError as e:
  print(type(e), e)

# We can solve the problem using either .contiguous() or .reshape()
x1 = x0.transpose(1, 2).contiguous().view(8, 3)
x2 = x0.transpose(1, 2).reshape(8, 3)
print('x1 shape: ', x1.shape)
print('x2 shape: ', x2.shape)

### Your turn

Given the 1-dimensional input tensor `x0` containing the numbers 0 through 23 in order, apply a sequence of reshaping operations to `x0` to create the following tensor:

```
x1 = tensor([[ 0,  1,  2,  3, 12, 13, 14, 15],
             [ 4,  5,  6,  7, 16, 17, 18, 19],
             [ 8,  9, 10, 11, 20, 21, 22, 23]])
```

Hint: You will need to create an intermediate tensor of rank 3

In [ ]:
x0 = torch.arange(24)
print('Here is x0:')
print(x0)

x1 = None
##############################################################################
# TODO: Use reshape operations to create x1 from x0                          #
##############################################################################
# Replace "pass" statement with your code
xx = x0.reshape(2, 3, 4)
xxx = xx.permute(1,0,2)
x1 = xxx.reshape(3,8)
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
print('\nHere is x1:')
print(x1)

expected = [
    [0, 1,  2,  3, 12, 13, 14, 15],
    [4, 5,  6,  7, 16, 17, 18, 19],
    [8, 9, 10, 11, 20, 21, 22, 23]]
print('Correct:', x1.tolist() == expected)

Here is x0:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

Here is x1:
tensor([[ 0,  1,  2,  3, 12, 13, 14, 15],
        [ 4,  5,  6,  7, 16, 17, 18, 19],
        [ 8,  9, 10, 11, 20, 21, 22, 23]])
Correct: True


## 张量操作

### Elementwise operations

基本数学函数对张量进行逐元素操作，可以作为运算符重载、`torch`模块中的函数以及torch对象的实例方法使用；所有这些方法产生的结果相同：

In [ ]:
x = torch.tensor([[1, 2, 3, 4]], dtype=torch.float32)
y = torch.tensor([[5, 6, 7, 8]], dtype=torch.float32)

# Elementwise sum; all give the same result
print('Elementwise sum:')
print(x + y)
print(torch.add(x, y))
print(x.add(y))

# Elementwise difference
print('\nElementwise difference:')
print(x - y)
print(torch.sub(x, y))
print(x.sub(y))

# Elementwise product
print('\nElementwise product:')
print(x * y)
print(torch.mul(x, y))
print(x.mul(y))

# Elementwise division
print('\nElementwise division')
print(x / y)
print(torch.div(x, y))
print(x.div(y))

# Elementwise power
print('\nElementwise power')
print(x ** y)
print(torch.pow(x, y))
print(x.pow(y))

Elementwise sum:
tensor([[ 6.,  8., 10., 12.]])
tensor([[ 6.,  8., 10., 12.]])
tensor([[ 6.,  8., 10., 12.]])

Elementwise difference:
tensor([[-4., -4., -4., -4.]])
tensor([[-4., -4., -4., -4.]])
tensor([[-4., -4., -4., -4.]])

Elementwise product:
tensor([[ 5., 12., 21., 32.]])
tensor([[ 5., 12., 21., 32.]])
tensor([[ 5., 12., 21., 32.]])

Elementwise division
tensor([[0.2000, 0.3333, 0.4286, 0.5000]])
tensor([[0.2000, 0.3333, 0.4286, 0.5000]])
tensor([[0.2000, 0.3333, 0.4286, 0.5000]])

Elementwise power
tensor([[1.0000e+00, 6.4000e+01, 2.1870e+03, 6.5536e+04]])
tensor([[1.0000e+00, 6.4000e+01, 2.1870e+03, 6.5536e+04]])
tensor([[1.0000e+00, 6.4000e+01, 2.1870e+03, 6.5536e+04]])


Torch 还提供了许多标准数学函数；这些函数既可以作为 `torch` 模块中的函数使用，也可以作为张量上的实例方法使用：

You can find a full list of all available mathematical functions [in the documentation](https://pytorch.org/docs/stable/torch.html#pointwise-ops); many functions in the `torch` module have corresponding instance methods [on tensor objects](https://pytorch.org/docs/stable/tensors.html).

In [ ]:
x = torch.tensor([[1, 2, 3, 4]], dtype=torch.float32)

print('Square root:')
print(torch.sqrt(x))
print(x.sqrt())

print('\nTrig functions:')
print(torch.sin(x))
print(x.sin())
print(torch.cos(x))
print(x.cos())

Square root:
tensor([[1.0000, 1.4142, 1.7321, 2.0000]])
tensor([[1.0000, 1.4142, 1.7321, 2.0000]])

Trig functions:
tensor([[ 0.8415,  0.9093,  0.1411, -0.7568]])
tensor([[ 0.8415,  0.9093,  0.1411, -0.7568]])
tensor([[ 0.5403, -0.4161, -0.9900, -0.6536]])
tensor([[ 0.5403, -0.4161, -0.9900, -0.6536]])


### Reduction operations

到目前为止，我们已经看到了对张量进行逐元素操作的基本算术运算。有时我们可能希望执行对张量的部分或全部进行聚合的操作，例如求和；这些称为 **归约(reduction)** 操作。

与上述逐元素操作类似，大多数归约操作既可以作为 `torch` 模块中的函数使用，也可以作为 `tensor` 对象上的实例方法使用。

最简单的归约操作是求和。我们可以使用 `.sum()` 函数来对整个张量进行归约，或者使用 `dim` 参数仅沿张量的一个维度进行归约：

In [ ]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]], dtype=torch.float32)
print('Original tensor:')
print(x)

print('\nSum over entire tensor:')
print(torch.sum(x))
print(x.sum())

# We can sum over each row:
print('\nSum of each row:')
print(torch.sum(x, dim=0))
print(x.sum(dim=0))

# Sum over each column:
print('\nSum of each column:')
print(torch.sum(x, dim=1))
print(x.sum(dim=1))

Original tensor:
tensor([[1., 2., 3.],
        [4., 5., 6.]])

Sum over entire tensor:
tensor(21.)
tensor(21.)

Sum of each row:
tensor([5., 7., 9.])
tensor([5., 7., 9.])

Sum of each column:
tensor([ 6., 15.])
tensor([ 6., 15.])


Other useful reduction operations include [`mean`](https://pytorch.org/docs/stable/torch.html#torch.mean), [`min`](https://pytorch.org/docs/stable/torch.html#torch.min), and [`max`](https://pytorch.org/docs/stable/torch.html#torch.max). You can find a full list of all available reduction operations [in the documentation](https://pytorch.org/docs/stable/torch.html#reduction-ops).

某些还原操作会返回多个值，例如 `min` 既返回指定维度上的最小值，也返回最小值所在的索引：

In [ ]:
x = torch.tensor([[2, 4, 3, 5], [3, 3, 5, 2]], dtype=torch.float32)
print('Original tensor:')
print(x, x.shape)

# Finding the overall minimum only returns a single value
print('\nOverall minimum: ', x.min())

# Compute the minimum along each column; we get both the value and location:
# 第一列的最小值是2，出现在索引0处；
# 第二列的最小值是3，出现在索引1处；等等。
col_min_vals, col_min_idxs = x.min(dim=0)
print('\nMinimum along each column:')
print('values:', col_min_vals)
print('idxs:', col_min_idxs)

# Compute the minimum along each row; we get both the value and the minimum
row_min_vals, row_min_idxs = x.min(dim=1)
print('\nMinimum along each row:')
print('values:', row_min_vals)
print('idxs:', row_min_idxs)

Original tensor:
tensor([[2., 4., 3., 5.],
        [3., 3., 5., 2.]]) torch.Size([2, 4])

Overall minimum:  tensor(2.)

Minimum along each column:
values: tensor([2., 3., 3., 2.])
idxs: tensor([0, 1, 0, 1])

Minimum along each row:
values: tensor([2., 2.])
idxs: tensor([0, 3])


归约操作会 *减少* 张量的秩：执行归约的维度将从输出的形状中移除。如果在归约操作中传递 `keepdim=True`，则指定的维度不会被移除；输出张量在该维度上将具有1的形状。

当处理多维张量时，考虑行和列可能会变得混乱；相反，考虑每个操作将产生的形状更有用。例如：

In [ ]:
# Create a tensor of shape (128, 10, 3, 64, 64)
x = torch.randn(128, 10, 3, 64, 64)
print(x.shape)

# Take the mean over dimension 1; shape is now (128, 3, 64, 64)
x = x.mean(dim=1)
print(x.shape)

# Take the sum over dimension 2; shape is now (128, 3, 64)
x = x.sum(dim=2)
print(x.shape)

# Take the mean over dimension 1, but keep the dimension from being eliminated
# by passing keepdim=True; shape is now (128, 1, 64)
x = x.mean(dim=1, keepdim=True)
print(x.shape)

torch.Size([128, 10, 3, 64, 64])
torch.Size([128, 3, 64, 64])
torch.Size([128, 3, 64])
torch.Size([128, 1, 64])


Your turn: use reduction and indexing operations to implement a function that sets the minimum value along each row of a tensor to zero.

Hint: [`torch.argmin`](https://pytorch.org/docs/stable/torch.html#torch.argmin)

In [ ]:
def zero_row_min(x):
  """
  Return a copy of x, where the minimum value along each row has been set to 0.

  For example, if x is:
  x = torch.tensor([[
        [10, 20, 30],
        [ 2,  5,  1]
      ]])

  Then y = zero_row_min(x) should be:
  torch.tensor([
    [0, 20, 30],
    [2,  5,  0]
  ])

  Inputs:
  - x: Tensor of rank 2 with shape (N, M)

  Returns:
  - y: Tensor of rank 2 that is a copy of x, except the minimum value along each
       row is replaced with 0.
  """
  y = x.clone()
  ##############################################################################
  # TODO: Complete the implementation of this function.                        #
  ##############################################################################
  # Replace "pass" statement with your code
  ind = torch.argmin(y,dim=1)
  for i in range(ind.shape[0]):
    y[i,ind[i]] = 0
  ##############################################################################
  #                             END OF YOUR CODE                               #
  ##############################################################################
  return y

Now test your implementation with a few small test cases:

In [ ]:
x0 = torch.tensor([[10, 20, 30], [2, 5, 1]])
print('Here is x0:')
print(x0)
y0 = zero_row_min(x0)
print('Here is y0:')
print(y0)
assert y0.tolist() == [[0, 20, 30], [2, 5, 0]]

x1 = torch.tensor([[2, 5, 10, -1], [1, 3, 2, 4], [5, 6, 2, 10]])
print('\nHere is x1:')
print(x1)
y1 = zero_row_min(x1)
print('Here is y1:')
print(y1)
assert y1.tolist() == [[2, 5, 10, 0], [0, 3, 2, 4], [5, 6, 0, 10]]

print('\nSimple tests pass!')

Here is x0:
tensor([[10, 20, 30],
        [ 2,  5,  1]])
Here is y0:
tensor([[ 0, 20, 30],
        [ 2,  5,  0]])

Here is x1:
tensor([[ 2,  5, 10, -1],
        [ 1,  3,  2,  4],
        [ 5,  6,  2, 10]])
Here is y1:
tensor([[ 2,  5, 10,  0],
        [ 0,  3,  2,  4],
        [ 5,  6,  0, 10]])

Simple tests pass!


### 矩阵操作

请注意，与 MATLAB 不同，* 是对应元素相乘，而不是矩阵乘法。PyTorch 提供了许多线性代数函数来计算不同类型的向量和矩阵乘积。最常用的是：

- [`torch.dot`](https://pytorch.org/docs/1.1.0/torch.html#blas-and-lapack-operations): Computes inner product of vectors
- [`torch.mm`](https://pytorch.org/docs/1.1.0/torch.html#torch.mm): Computes matrix-matrix products
- [`torch.mv`](https://pytorch.org/docs/1.1.0/torch.html#torch.mv): Computes matrix-vector products
- [`torch.addmm`](https://pytorch.org/docs/1.1.0/torch.html#torch.addmm) / [`torch.addmv`](https://pytorch.org/docs/1.1.0/torch.html#torch.addmv): Computes matrix-matrix and matrix-vector multiplications plus a bias
- [`torch.bmm`](https://pytorch.org/docs/1.1.0/torch.html#torch.addmv) / [`torch.baddmm`](https://pytorch.org/docs/1.1.0/torch.html#torch.baddbmm): Batched versions of `torch.mm` and `torch.addmm`, respectively
- [`torch.matmul`](https://pytorch.org/docs/1.1.0/torch.html#torch.matmul): General matrix product that performs different operations depending on the rank of the inputs; this is similar to `np.dot` in numpy.

You can find a full list of the available linear algebra operators [in the documentation](https://pytorch.org/docs/1.1.0/torch.html#blas-and-lapack-operations).

以下是使用 `torch.dot` 计算内积的示例。与我们见过的其他数学运算符一样，大多数线性代数运算符既可以作为 `torch` 模块中的函数使用，也可以作为张量的实例方法使用：

In [ ]:
v = torch.tensor([9,10], dtype=torch.float32)
w = torch.tensor([11, 12], dtype=torch.float32)

# Inner product of vectors
print('Dot products:')
print(torch.dot(v, w))
print(v.dot(w))

# dot only works for vectors -- it will give an error for tensors of rank > 1 只有一维张量才能用 dot 方法
x = torch.tensor([[1,2],[3,4]], dtype=torch.float32)
y = torch.tensor([[5,6],[7,8]], dtype=torch.float32)
try:
  print(x.dot(y))
except RuntimeError as e:
  print(e)

# Instead we use mm for matrix-matrix products: 二维张量就要用 mm 方法
print('\nMatrix-matrix product:')
print(torch.mm(x, y))
print(x.mm(y))

Dot products:
tensor(219.)
tensor(219.)
1D tensors expected, but got 2D and 2D tensors

Matrix-matrix product:
tensor([[19., 22.],
        [43., 50.]])
tensor([[19., 22.],
        [43., 50.]])


PyTorch 提供了多种线性代数运算符，通常有不止一种方法来计算某个操作。例如，要计算矩阵向量乘积，我们可以使用 `torch.mv`；我们可以将向量重塑为秩为2的张量并使用 `torch.mm`；或者我们可以使用 `torch.matmul`。所有方法都会得到相同的结果，但输出的秩可能不同：

In [ ]:
print('Here is x (rank 2):')
print(x)
print('\nHere is v (rank 1):')
print(v)

# Matrix-vector multiply with torch.mv produces a rank-1 output
print('\nMatrix-vector product with torch.mv (rank 1 output)')
print(torch.mv(x, v))
print(x.mv(v))

# We can reshape the vector to have rank 2 and use torch.mm to perform
# matrix-vector products, but the result will have rank 2
print('\nMatrix-vector product with torch.mm (rank 2 output)')
print(torch.mm(x, v.view(2, 1)))
print(x.mm(v.view(2, 1)))

print('\nMatrix-vector product with torch.matmul (rank 1 output)')
print(torch.matmul(x, v))
print(x.matmul(v))

Here is x (rank 2):
tensor([[1., 2.],
        [3., 4.]])

Here is v (rank 1):
tensor([ 9., 10.])

Matrix-vector product with torch.mv (rank 1 output)
tensor([29., 67.])
tensor([29., 67.])

Matrix-vector product with torch.mm (rank 2 output)
tensor([[29.],
        [67.]])
tensor([[29.],
        [67.]])

Matrix-vector product with torch.matmul (rank 1 output)
tensor([29., 67.])
tensor([29., 67.])


Your turn: use [`torch.bmm`](https://pytorch.org/docs/1.1.0/torch.html#torch.bmm) to perform a batched matrix multiply.

对存储在 batch1 和 batch2 中的矩阵执行批量矩阵乘法。

batch1 和 batch2 必须是每个包含相同数量矩阵的三维张量。

In [ ]:
B, N, M, P = 3, 2, 5, 4
x = torch.rand(B, N, M)  # Random tensor of shape (B, N, M)
y = torch.rand(B, M, P)  # Random tensor of shape (B, M, P)

# We can use a for loop to (inefficiently) compute a batch of matrix multiply
# operations
z1 = torch.empty(B, N, P)  # Empty tensor of shape (B, N, P)
for i in range(B):
  z1[i] = x[i].mm(y[i])
print('Here is the result of batched matrix multiply with a loop:')
print(z1)

z2 = None
##############################################################################
# TODO: Use bmm to compute a batched matrix multiply between x and y; store  #
# the result in z2.                                                          #
##############################################################################
# Replace "pass" statement with your code
z2 = torch.bmm(x,y)
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
print('\nHere is the result of batched matrix multiply with bmm:')
print(z2)

# The two may not return exactly the same result; different linear algebra
# routines often return slightly different results due to the fact that
# floating-point math is non-exact and non-associative.
diff = (z1 - z2).abs().max().item()
print('\nDifference:', diff)
print('Difference within threshold:', diff < 1e-6)

Here is the result of batched matrix multiply with a loop:
tensor([[[0.9347, 0.7368, 1.1844, 1.1910],
         [1.1043, 0.5611, 0.8835, 0.9876]],

        [[0.7110, 0.8649, 1.5978, 0.7247],
         [1.3722, 1.4697, 2.7334, 1.8557]],

        [[0.7202, 1.7190, 0.6937, 1.7407],
         [0.4594, 0.9283, 0.5929, 0.5578]]])

Here is the result of batched matrix multiply with bmm:
tensor([[[0.9347, 0.7368, 1.1844, 1.1910],
         [1.1043, 0.5611, 0.8835, 0.9876]],

        [[0.7110, 0.8649, 1.5978, 0.7247],
         [1.3722, 1.4697, 2.7334, 1.8557]],

        [[0.7202, 1.7190, 0.6937, 1.7407],
         [0.4594, 0.9283, 0.5929, 0.5578]]])

Difference: 2.384185791015625e-07
Difference within threshold: True


## Broadcasting

广播（Broadcasting）是一种强大的机制，使得PyTorch在进行算术运算时能够处理不同形状的数组。通常我们有一个较小的张量和一个较大的张量，我们希望多次使用较小的张量对较大的张量执行某些操作。

例如，假设我们想将一个常量向量加到张量的每一行上。我们可以这样做：

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print("Before:\n",x)
v = torch.tensor([1, 0, 1])
y = torch.zeros_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v #

print(y)

Before:
 tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
tensor([[ 2,  2,  4],
        [ 5,  5,  7],
        [ 8,  8, 10],
        [11, 11, 13]])


此方法可行；然而，当张量 x 非常大时，在 Python 中显式地计算循环可能会很慢。请注意，将向量 v 加到张量 x 的每一行上，等同于通过垂直堆叠 v 的多个副本来形成张量 vv，然后对 x 和 vv 进行逐元素求和。我们可以这样实现这种方法：

In [ ]:
vv = v.repeat((4, 1))  # Stack 4 copies of v on top of each other
print(vv)              # Prints "[[1 0 1]
                       #          [1 0 1]
                       #          [1 0 1]
                       #          [1 0 1]]"

tensor([[1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1]])


In [ ]:
y = x + vv  # Add x and vv elementwise
print(y)

tensor([[ 2,  2,  4],
        [ 5,  5,  7],
        [ 8,  8, 10],
        [11, 11, 13]])


PyTorch的广播机制使我们能够在不实际创建v的多个副本的情况下执行此计算。考虑这样使用广播机制：

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = torch.tensor([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

tensor([[ 2,  2,  4],
        [ 5,  5,  7],
        [ 8,  8, 10],
        [11, 11, 13]])


尽管 x 的形状是 (4, 3) 而 v 的形状是 (3,)，由于广播机制，直线 y = x + v 仍然有效；这条直线的工作原理就像是 v 实际上具有形状 (4, 3)，其中每一行都是 v 的副本，并且求和是逐元素进行的。

广播两个张量遵循以下规则：

1. 如果张量的秩不同，则在较低秩张量的形状前添加1，直到两者的形状长度相同。

2. 如果两个张量在某维度上的大小相同，或者其中一个张量在该维度上的大小为1，则称这两个张量在该维度上是*兼容*的。

3. 如果两个张量在所有维度上都兼容，则它们可以一起广播。

4. 广播后，每个张量的行为就好像它的形状等于两个输入张量形状的逐元素最大值。

5. 在任意一个张量大小为1而另一个张量大小大于1的维度上，第一个张量的行为就好像它在该维度上被复制了一样。

If this explanation does not make sense, try reading the explanation from the [documentation](https://pytorch.org/docs/stable/notes/broadcasting.html).

Not all functions support broadcasting. You can find functions that does not support broadcasting from the official docs. (e.g. [`torch.mm`](https://pytorch.org/docs/stable/torch.html#torch.mm) does not support broadcasting, but [`torch.matmul`](https://pytorch.org/docs/1.1.0/torch.html#torch.matmul) does)

Broadcasting can let us easily implement many different operations. For example we can compute an outer product of vectors:

In [ ]:
# Compute outer product of vectors
v = torch.tensor([1, 2, 3])  # v has shape (3,)
w = torch.tensor([4, 5])     # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# 要计算外积，我们首先将 v 重塑为形状为 (3, 1) 的列向量；然后我们可以将其与 w 进行广播，得到形状为 (3, 2) 的输出，这就是 v 和 w 的外积，这两个张量可以广播，依照的是上面的规则2：
print(v.view(3, 1) * w)

tensor([[ 4,  5],
        [ 8, 10],
        [12, 15]])


We can add a vector to each row of a matrix:

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])  # x has shape (2, 3)
v = torch.tensor([1, 2, 3])               # v has shape (3,)
print('Here is the matrix:')
print(x)
print('\nHere is the vector:')
print(v)

# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
print('\nAdd the vector to each row of the matrix:')
print(x + v)

Here is the matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])

Here is the vector:
tensor([1, 2, 3])

Add the vector to each row of the matrix:
tensor([[2, 4, 6],
        [5, 7, 9]])


We can add a vector to each column of a matrix:

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])  # x has shape (2, 3)
w = torch.tensor([4, 5])                  # w has shape (2,)
print('Here is the matrix:')
print(x)
print('\nHere is the vector:')
print(w)

# x has shape (2, 3) and w has shape (2,). We reshape w to (2, 1);
# then when we add the two the result broadcasts to (2, 3):
print('\nAdd the vector to each column of the matrix:')
print(x + w.view(-1, 1))

# Another solution is the following:
# 1. Transpose x so it has shape (3, 2)
# 2. Since w has shape (2,), adding will broadcast to (3, 2)
# 3. Transpose the result, resulting in a shape (2, 3)
print((x.t() + w).t())

Here is the matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])

Here is the vector:
tensor([4, 5])

Add the vector to each column of the matrix:
tensor([[ 5,  6,  7],
        [ 9, 10, 11]])
tensor([[ 5,  6,  7],
        [ 9, 10, 11]])


Multiply a tensor by a set of constants:

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])  # x has shape (2, 3)
c = torch.tensor([1, 10, 11, 100])        # c has shape (4)
print('Here is the matrix:')
print(x)
print('\nHere is the vector:')
print(c)

# 执行以下操作：
# 1. 将 c 从形状 (4,) 重塑为 (4, 1, 1)
# 2. x 的形状为 (2, 3)。由于它们的秩不同，当我们相乘时，x 的形状被自动调整为 (1, 2, 3)
# 3. 形状为 (4, 1, 1) 和 (1, 2, 3) 的张量进行广播乘法的结果形状为 (4, 2, 3)
# 4. 结果 y 的形状为 (4, 2, 3)，并且 y[i]（形状为 (2, 3)）等于 c[i] * x
y = c.view(-1, 1, 1) * x
print('\nMultiply x by a set of constants:')
print(y)

Here is the matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])

Here is the vector:
tensor([  1,  10,  11, 100])

Multiply x by a set of constants:
tensor([[[  1,   2,   3],
         [  4,   5,   6]],

        [[ 10,  20,  30],
         [ 40,  50,  60]],

        [[ 11,  22,  33],
         [ 44,  55,  66]],

        [[100, 200, 300],
         [400, 500, 600]]])


Your turn: 编写一个函数，用于标准化矩阵的列。该函数应计算每列的均值和标准差，然后对每列中的每个元素减去均值并除以标准差。

Example:
```
x = [[ 0,  30,  600],
     [ 1,  10,  200],
     [-1,  20,  400]]
```
- The first column has mean 0 and std 1
- The second column has mean 20 and std 10
- The third column has mean 400 and std 200

After normalizing the columns, the result should be:
```
y = [[ 0,  1,  1],
     [ 1, -1, -1],
     [-1,  0,  0]]
```

In [ ]:
def normalize_columns(x):
  """
  Normalize the columns of a matrix by subtracting the mean and dividing by the
  standard deviation.

  Inputs:
  - x: Tensor of shape (N, M)

  Returns:
  - y: Tensor of shape (N, M) which is a copy of x with normalized columns.
  """
  y = x.clone()
  ##############################################################################
  # TODO: Complete the implementation of this function. Do not modify x.       #
  # Your implementation should not use any loops; instead you should use       #
  # reduction and broadcasting operations.                                     #
  ##############################################################################
  # Replace "pass" statement with your code
  mean = y.mean(dim=0,keepdim=True)
  std = y.std(dim=0,keepdim=True)
  y = (y - mean) / std
  ##############################################################################
  #                             END OF YOUR CODE                               #
  ##############################################################################
  return y

Now test your implementation with a simple test:

In [ ]:
x0 = torch.tensor([[0., 30., 600.], [1., 10., 200.], [-1., 20., 400.]])
y0 = normalize_columns(x0)
print('Here is x0:')
print(x0)
print('Here is y0:')
print(y0)
assert y0.tolist() == [[0., 1., 1.], [1., -1., -1.], [-1., 0., 0.]]
assert x0.tolist() == [[0., 30., 600.], [1., 10., 200.], [-1., 20., 400.]]

Here is x0:
tensor([[  0.,  30., 600.],
        [  1.,  10., 200.],
        [ -1.,  20., 400.]])
Here is y0:
tensor([[ 0.,  1.,  1.],
        [ 1., -1., -1.],
        [-1.,  0.,  0.]])


**解析**

以本案例为例， y 的 shape 为 `torch.Size([3, 3])`

```python
mean = y.mean(dim=0,keepdim=True) # tensor([0,20,400])
std = y.std(dim=0,keepdim=True) # tensor([1,10,200])
```

这两个都是 `torch.Size([1, 3])` 的张量，与 y 进行运算时，他们都会自动广播为 `torch.Size([3, 3])`，广播后的张量为

```python
# mean
tensor([
    [0,20,400],
    [0,20,400],
    [0,20,400]
    ])

#std
tensor([
    [1,10,200],
    [1,10,200],
    [1,10,200]
    ])
```

## Running on GPU

PyTorch最重要的特性之一是它能够利用图形处理单元（GPU）来加速其张量操作。

我们可以轻松检查PyTorch是否配置为使用GPU：

张量可以使用`.to`方法移动到任何设备上。

In [1]:
import torch

if torch.cuda.is_available:
  print('PyTorch can use GPUs!')
else:
  print('PyTorch cannot use GPUs.')

PyTorch can use GPUs!


你可以在Colab中通过以下路径启用GPU：运行时 -> 更改运行时类型 -> 硬件加速器 -> GPU。

这可能会导致Colab运行时重启，因此我们将在下一个单元格中重新导入torch。

我们已经知道PyTorch张量有一个`dtype`属性，用于指定其数据类型。所有PyTorch张量还有一个`device`属性，用于指定张量存储的设备——可以是CPU，或者是CUDA（适用于NVIDIA GPU）。位于CUDA设备上的张量将自动使用该设备来加速其所有操作。

与数据类型一样，我们可以使用 [`.to()`](https://pytorch.org/docs/1.1.0/tensors.html#torch.Tensor.to) 方法来更改张量的设备。我们还可以使用便捷的 `.cuda()` 和 `.cpu()` 方法在CPU和GPU之间移动张量。

In [2]:
# Construct a tensor on the CPU
x0 = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
print('x0 device:', x0.device)

# Move it to the GPU using .to()
x1 = x0.to('cuda')
print('x1 device:', x1.device)

# Move it to the GPU using .cuda()
x2 = x0.cuda()
print('x2 device:', x2.device)

# Move it back to the CPU using .to()
x3 = x1.to('cpu')
print('x3 device:', x3.device)

# Move it back to the CPU using .cpu()
x4 = x2.cpu()
print('x4 device:', x4.device)

# We can construct tensors directly on the GPU as well
y = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float64, device='cuda')
print('y device / dtype:', y.device, y.dtype)

# Calling x.to(y) where y is a tensor will return a copy of x with the same
# device and dtype as y
x5 = x0.to(y)
print('x5 device / dtype:', x5.device, x5.dtype)

x0 device: cpu
x1 device: cuda:0
x2 device: cuda:0
x3 device: cpu
x4 device: cpu
y device / dtype: cuda:0 torch.float64
x5 device / dtype: cuda:0 torch.float64


在GPU上执行大型张量操作比在CPU上运行等效操作要**快得多**。

这里我们比较在CPU和GPU上对两个形状为(10000, 10000)的张量进行相加的速度：

（注意，GPU代码可能与CPU代码异步运行，因此在计时GPU操作速度时，使用`torch.cuda.synchronize`来同步CPU和GPU非常重要。）

In [3]:
import time

a_cpu = torch.randn(10000, 10000, dtype=torch.float32)
b_cpu = torch.randn(10000, 10000, dtype=torch.float32)

a_gpu = a_cpu.cuda()
b_gpu = b_cpu.cuda()
torch.cuda.synchronize()

t0 = time.time()
c_cpu = a_cpu + b_cpu
t1 = time.time()
c_gpu = a_gpu + b_gpu
torch.cuda.synchronize()
t2 = time.time()

# Check that they computed the same thing
diff = (c_gpu.cpu() - c_cpu).abs().max().item()
print('Max difference between c_gpu and c_cpu:', diff)

cpu_time = 1000.0 * (t1 - t0)
gpu_time = 1000.0 * (t2 - t1)
print('CPU time: %.2f ms' % cpu_time)
print('GPU time: %.2f ms' % gpu_time)
print('GPU speedup: %.2f x' % (cpu_time / gpu_time))

Max difference between c_gpu and c_cpu: 0.0
CPU time: 268.42 ms
GPU time: 55.88 ms
GPU speedup: 4.80 x


你应该注意到，在GPU上运行相同的计算比在CPU上快了30多倍！由于GPU提供了巨大的加速，我们将从作业2开始使用GPU来加速大部分机器学习代码。

轮到你了：使用GPU来加速以下矩阵乘法操作。通过使用GPU，你应该能看到大约10倍的加速。

In [9]:
import time

x = torch.rand(512, 4096)
w = torch.rand(4096, 4096)

t0 = time.time()
y0 = x.mm(w)
t1 = time.time()

y1 = None
##############################################################################
# TODO: Write a bit of code that performs matrix multiplication of x and w   #
# on the GPU, and then moves the result back to the CPU. Store the result    #
# in y1.
##############################################################################
# Replace "pass" statement with your code
x_gpu = x.to('cuda')
w_gpu = w.to('cuda')
y1 = x_gpu.mm(w_gpu)
y1 = y1.to('cpu')
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
torch.cuda.synchronize()
t2 = time.time()

print('y1 on CPU:', y1.device == torch.device('cpu'))
diff = (y0 - y1).abs().max().item()
print('Max difference between y0 and y1:', diff)
print('Difference within tolerance:', diff < 5e-2)

cpu_time = 1000.0 * (t1 - t0)
gpu_time = 1000.0 * (t2 - t1)
print('CPU time: %.2f ms' % cpu_time)
print('GPU time: %.2f ms' % gpu_time)
print('GPU speedup: %.2f x' % (cpu_time / gpu_time))

y1 on CPU: True
Max difference between y0 and y1: 0.001220703125
Difference within tolerance: True
CPU time: 151.09 ms
GPU time: 30.87 ms
GPU speedup: 4.89 x
